version: '3.7'
services:
  service-2:
    image: stegojulia/project2s2
    deploy: 
      replicas: 3
      update_config:
        order: start-first
    build: ./service-2
    ports:
    - 5012:5012
    restart: always
  service-1:
    image: stegojulia/project2s1
    deploy: 
      replicas: 3
      update_config:
        order: start-first
    build: ./service-1
    ports:
    - 5011:5011
    restart: always
    depends_on:
      - "service-2"
      - "service-3"
      - "service-4"
  service-3:
    image: stegojulia/project2s3
    deploy: 
      replicas: 3
      update_config:
        order: start-first
    build: ./service-3
    ports:
    - 5002:5002
    restart: always
    depends_on:
      - "service-2"
  service-4:
    image: stegojulia/project2s4
    deploy: 
      replicas: 3
      update_config:
        order: start-first
    build: ./service-4
    ports:
    - 5003:5003
    restart: always
    depends_on:
      - "service-2"


