- hosts: all
  roles:
    - docker
- hosts: manager
  roles:
    - swarm-init
- hosts: worker
  roles:
    - swarm-join
- hosts: nginx
  roles:
    - webserver
- hosts: localhost
  connection: local 
  roles:
    - image-build
- hosts: manager
  roles:
    - docker-stack



