
# tasks file for webserver
- name: Install NGINX
  apt:
    name: nginx
    state: latest
    update_cache: true
  become: yes
- name: Add nginx conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  become: yes
- name: Start NGINX Service
  service:
    name: nginx
    state: started
  become: yes


